### ISSUE TITLE
Does not install trelliscopejs

### ISSUE THREAD

**Issue by stefvanbuuren** [HBGDki/hbgd#14]
Hi Ryan, 

Tried to run 

`devtools::install_github("hafen/hbgd")`

but got

`ERROR: dependency ‘trelliscopejs’ is not available for package ‘hbgd’`

Any idea what could be the problem?
Stef.

**Comment by hafen** [comment]
Hi Stef,

Sorry about that. Can you try now? Hopefully I fixed it but I can’t test because my internet is out and I’m on a weak cell signal.

Ryan

--
Ryan Hafen
Hafen Consulting, LLC
http://ryanhafen.com <http://ryanhafen.com/>
@hafenstats <https://twitter.com/hafenstats>

**Comment by stefvanbuuren** [comment]
Ryan, thanks for the ultra-speedy fix. It works now. All the best, Stef.
